kind: pipeline
name: default

steps:
- name: run-koa-react-starter-tests
  image: node:10.16.0
  commands:
  - chmod +x ./bin/run.sh
  - ./bin/run.sh
  when:
    event:
    - pull_request
    - push

trigger:
  branch:
  - master
